source 'https://rubygems.org'
ruby '2.2.1'

gem 'rails', '4.1.5'
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise', '~> 3.3.0'
gem 'acts_as_votable', '~> 0.10.0'
gem 'simple_form', '~> 3.1.0'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'sqlite3'
gem 'impressionist'
gem 'rails_admin', '~> 0.6.8'
gem 'will_paginate', '~> 3.0.7'
gem 'will_paginate-bootstrap', '~> 1.0.1'
gem 'zurb-foundation', '~> 4.3.2'
gem 'therubyracer', '~> 0.12.2'
gem 'onliner'
gem 'redis', '~> 3.0.6'
gem 'redis-namespace', '~> 1.5.2'
group :development do
    gem 'better_errors', '~> 2.1.1'
    gem 'binding_of_caller', '~> 0.7.2'
    gem 'spring'
    gem 'annotate', '~> 2.6.10'
end